[project]
name = "birdwatcher-app-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.0",
    "streamlit>=1.43.2",
    "streamlit-javascript>=0.1.5",
]
